name: test

on: [push] 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Var expansion
      run: ./print-first-arg.sh ${GITHUB_REF#refs/tags/}
